### GET
GET http://localhost:3003/api/blogs

### POST
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVrYWkiLCJpZCI6IjYwMzEyNTI4MjQzMjYzNDA0OGYwMTJiMCIsImlhdCI6MTYxMzgzMzkwOH0.Yz0p7nDy0_q_cfER8mBNfv6SnvZn8P6rTw8OwzAkpNI

{
    'title': 'My Blog',
    'author': 'Christoph Schaefer',
    'url': 'www.my-personal-blog.de',
    'likes': 100
}

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    'username': 'hellas',
    'name': 'Arto Hellas',
    'password': '1234'
}

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    'username': 'mluukai',
    'name': 'Matti Luukkainen',
    'password': 'salainen'
}

### PUT
PUT http://localhost:3003/api/blogs/5a422aa71b54a676234d17f8 HTTP/1.1
content-type: application/json

{
    'title': 'My Blog',
    'author': 'Christoph Schaefer',
    'url': 'www.my-personal-blog.de',
    'likes': 1234
}

###
DELETE http://localhost:3003/api/blogs/60310f2e5adf5a0a6c4da198

###
post http://localhost:3003/api/login
Content-Type:  application/json

{
    'username': 'mluukai',
    'password': 'salainen'
}